# -*- coding: utf-8 -*-
"""text_to_image1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bKD_djwo2EUmZmjUHxvSl2jyz-R70EGN
"""

pip install diffusers transformers accelerate scipy torch

# Step 1: Import necessary libraries
import torch
from diffusers import StableDiffusionPipeline
import matplotlib.pyplot as plt
import os

# Step 2: Load the Stable Diffusion pipeline
model_id = "runwayml/stable-diffusion-v1-5"  # You can try other models too
device = "cuda" if torch.cuda.is_available() else "cpu"

pipe = StableDiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16 if device == "cuda" else torch.float32
)
pipe = pipe.to(device)

# Step 3: Define your text prompt and parameters
prompt = "A girl with long hair sitting by the window with a book and a cup of coffee, cozy aesthetic"  # ← change as desired
num_inference_steps = 80  # Controls generation steps (more = better quality)
guidance_scale = 7.5      # Higher = more faithful to prompt
height = 512              # Output image height
width = 512               # Output image width
seed = 42                 # For reproducibility (change for variety)

# Set random generator for reproducibility
generator = torch.manual_seed(seed)

# Step 4: Generate the image
image = pipe(
    prompt=prompt,
    height=height,
    width=width,
    num_inference_steps=num_inference_steps,
    guidance_scale=guidance_scale,
    generator=generator
).images[0]

# Step 5: Show and save the result
import matplotlib.pyplot as plt

# Display in notebook or script
plt.imshow(image)
plt.axis("off")
plt.title("Generated Image")
plt.show()

# Optional: Save the image locally
output_dir = "outputs"
os.makedirs(output_dir, exist_ok=True)
image.save(os.path.join(output_dir, "generated_image.png"))